export const menu=[
    {
        id:1,
        title:"main",
        listItems:[
            {
                id:1,
                title:"Homepage",
                URL:"/",
                icon:"home.svg",
            },
            {
                id:2,
                title:"user",
                URL:"/users",
                icon:"user.svg",
            },
        ],
    },
    {
        id:2,
        title:"Lists",
        listItems:[
            {
                id:1,
                title:"products",
                URL:"/products",
                icon:"product.svg",
            },
            {
                id:2,
                title:"settings",
                URL:"/setting",
                icon:"setting.svg",
            },
            {
                id:3,
                title:"profile",
                URL:"/profile",
                icon:"profile.svg",
            },
            {
                id:4,
                title:"report",
                URL:"/report",
                icon:"user.svg",
            },
        ],
    },
    {
        id:3,
        title:"Notice",
        listItems:[
            {
                id:1,
                title:"products",
                URL:"/products",
                icon:"product.svg",
            },
            {
                id:2,
                title:"settings",
                URL:"/setting",
                icon:"setting.svg",
            },
            {
                id:3,
                title:"profile",
                URL:"/profile",
                icon:"profile.svg",
            },
            {
                id:4,
                title:"report",
                URL:"/report",
                icon:"user.svg",
            },
        ],
    },
    {
        id:4,
        title:"maintenance",
        listItems:[
            {
                id:1,
                title:"products",
                URL:"/products",
                icon:"product.svg",
            },
            {
                id:2,
                title:"settings",
                URL:"/setting",
                icon:"setting.svg",
            },
            {
                id:3,
                title:"profile",
                URL:"/profile",
                icon:"profile.svg",
            },
            {
                id:4,
                title:"report",
                URL:"/report",
                icon:"user.svg",
            },
        ],
    },
];

